nom-tam-fits/nom-tam-fits

src/main/java/nom/tam/fits/BinaryTable.java, src/main/java/nom/tam/image/compression/hdu/CompressedTableHDU.java, src/main/java/nom/tam/util/ColumnTable.java
@TomMcGlynn the rowSize attribute caused problems during the binary compression implementation. And will also cause problems when you add a empty column (no rows yet) and add the rows afterward (fixed that in the head).  
But the rowSize attribute is redundant and not necessary, as far as I can see. This pull request contains the changes necessary to delete the attribute, and still have all tests succeed.
@TomMcGlynn could you verify, that my change is correct? If it is just push the merge pull request button.
=> removal of redundent attribute "rowSize" 

src/main/java/nom/tam/fits/AsciiTableHDU.java, src/main/java/nom/tam/fits/BasicHDU.java, src/main/java/nom/tam/fits/BinaryTable.java, src/main/java/nom/tam/fits/BinaryTableHDU.java, src/main/java/nom/tam/fits/Fits.java
This pull request is focused on resolving occurrences of Sonar rule 
squid:S1213 - The members of an interface declaration or class should appear in a pre-defined order.
You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S1213
Please let me know if you have any questions.
Soso Tughushi
=> Code quality fix - The members of an interface declaration or class should appear in a pre-defined order (part 1)

src/test/java/nom/tam/fits/util/BlackBoxImages.java, src/test/java/nom/tam/image/tile/operation/Access.java, src/test/java/nom/tam/util/TestArrayFuncs.java, src/test/java/nom/tam/util/test/ThrowAnyException.java
This pull request is focused on resolving occurrences of Sonar rule 
squid:S1118 - “Utility classes should not have public constructors ”. 
You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S1118
Please let me know if you have any questions.
Soso Tughushi
=> Fix: squid:S1118, Utility classes should not have public constructors

.gitignore, src/main/java/nom/tam/fits/HeaderCard.java, src/main/java/nom/tam/fits/TableHDU.java, src/test/java/nom/tam/fits/test/BinaryTableTest.java, src/test/java/nom/tam/fits/test/HeaderCardTest.java, src/test/java/nom/tam/fits/test/HeaderTest.java
Removed the explicit '+' from the exponent of the scientific notation format (wasn't needed).
Added a scientific notation version of setColumnMeta method to TableHDU
=> Minor fixes prior to release

src/main/java/nom/tam/fits/FitsFactory.java, src/test/java/nom/tam/fits/test/HeaderCardTest.java
This is a forwarding followup of the short discussion in commit [fd527d6](https://github.com/Starlink/starjava/commit/fd527d661efe04b05b368051df2bf6a6aa7329c3#commitcomment-23745202) from @mbtaylor:
> Change the static setting that determines whether the `nom.tam.fits` libraries recognise the [ESO HIERARCH convention for hierarchical FITS keywords](https://fits.gsfc.nasa.gov/registry/hierarch_keyword.html) from false (which is how it is configured by default) to true.
> 
> This setting is required to make the hierarchical variant of the WideFits convention work (see [`uk.ac.starlink.fits.WideFits`](https://github.com/Starlink/starjava/blob/master/fits/src/main/uk/ac/starlink/fits/WideFits.java)). There's no way in the nom.tam.fits API to configure HIERARCH-use on a per-call basis, so we …
=> set FitsFactory.useHierarch to true

src/main/java/nom/tam/fits/HeaderCard.java
When a header card is created with a non-ASCII or control char, this may result in a corrupted FITS file.
The attached (rebased) patch [6cc2947](https://github.com/Starlink/starjava/commit/6cc2947a088c8769f1e362a59daeb5b2864e93bb) from @mbtaylor ensures that only valid chars are written to FITS.
Without this patch, the according test in [Starjava `uk.ac.starlink.fits.Tamfits`](https://github.com/Starlink/starjava/blob/0c9f0da084c3c136dc485969a21edc4b6016a208/fits/src/testcases/uk/ac/starlink/fits/TamfitsTest.java#L46-L57) will fail.
=> Fix serious FITS character handling bug

src/main/java/nom/tam/fits/FitsDate.java, src/test/java/nom/tam/fits/FitsDateTest.java
FitsDate does not manage correctly the sub-second part of a date.
The following strings are valid ISO-8601 dates that are not correctly parsed and generate an exception:
```
"2018-11-28T12:13:14.1"
"2018-11-28T12:13:14.1234"
"2018-11-28T12:13:14.123456"
```
This PR fixes this problem.
=>  Fix management of sub-seconds in FitsDate

src/main/java/nom/tam/fits/Fits.java
with extended stack trace and suggestion to try `setAllowTerminalJunk(true)`.
=> More informative error from reading corrupted FITS files

src/main/java/nom/tam/fits/Fits.java, src/main/java/nom/tam/fits/Header.java, src/main/java/nom/tam/util/ArrayDataInput.java, src/main/java/nom/tam/util/ArrayDataOutput.java, src/main/java/nom/tam/util/ArrayDecoder.java, src/main/java/nom/tam/util/FitsFile.java, src/main/java/nom/tam/util/FitsInputStream.java, src/main/java/nom/tam/util/FitsOutputStream.java, src/main/java/nom/tam/util/RandomAccess.java, src/site/markdown/index.md, src/test/java/nom/tam/fits/HeaderTest.java, src/test/java/nom/tam/fits/ImageProtectedTest.java, src/test/java/nom/tam/fits/TruncatedFileExceptionTest.java, src/test/java/nom/tam/util/DefaultMethodsTest.java, src/test/java/nom/tam/util/FitsFileTest.java
- Move and hide `checkTruncated()` method to leave `ArrayDataInput` interface unperturbed. (Thanks to @mbtaylor for finding it as a potentially breaking change that was not necessary)
=> 1.16.0-rc3

pom.xml
The scopes of `javax.annotations` and `...findbugs:annotations` are set/changed to `compile`.
=> annotations dependencies scope set to 'compile'

pom.xml, src/changes/changes.xml
The pom defined to use the `source` and `target` compiler options to specify compatibility mode. However, it is a known issue that the resulting code is not fully Java 8 compatible, and breaks some functionality. This is why Java 9 introduced a `release` option instead. So going forward, this is the option we shall use for the maven build. 
The change means that packages can no longer be built using Java 8's compiler, but will require Java 9 or later. However, it is the only certain way to provide the assurance that the binary distribution of the library is fully Java 8 compatible.
=> pom.xml: Use release compiler option for Java 8 compatibility

src/main/java/nom/tam/fits/Header.java, src/main/java/nom/tam/fits/HeaderCardParser.java, src/test/java/nom/tam/fits/test/DupTest.java, src/test/java/nom/tam/fits/test/JunkTest.java
Dupes found when parsing (3rd party) headers,  used to be reported to `Header`'s `Logger`, but should be parsing specific, and thus be reported through `HeaderCardParser`'s separate logger instead to allow for distinct verbosity control through `Header.setParserWarningsEnabled()`.
=> Report dupes consistently via header parser's logger.

src/main/java/nom/tam/fits/Header.java, src/test/java/nom/tam/fits/test/DupTest.java
The changes in this PR are:
1. Warn only once for each keyword that has multiple assignments in the parse header.
2. new method `Header.getDuplicateKeySet()`, which returns the set of keywords that had duplicate assignments, or `null` if there were no keyword was assigned more than once.
=> Suppress repeated duplicate warnings & improve checks

src/main/java/nom/tam/fits/BasicHDU.java, src/main/java/nom/tam/fits/Header.java, src/main/java/nom/tam/fits/HeaderCard.java, src/main/java/nom/tam/fits/HeaderOrder.java, src/main/java/nom/tam/fits/header/FitsHeaderImpl.java, src/main/java/nom/tam/util/HashedList.java, src/test/java/nom/tam/fits/BasicHduFailureTest.java, src/test/java/nom/tam/fits/HeaderOrderTest.java, src/test/java/nom/tam/fits/HeaderTest.java, src/test/java/nom/tam/fits/KeyTypeTest.java, src/test/java/nom/tam/fits/test/BaseFitsTest.java, src/test/java/nom/tam/fits/test/DupTest.java, src/test/java/nom/tam/fits/test/JunkTest.java
- Move implementation from `BasicHDU.setPrimary(boolean)` to new public `Header.validate(boolean)`, and deal with all required keywords, as well as order and END.
- Change `Header.addValue(IFitsHeader...)` to call `HeaderCard.create(IFitsHeader...)` with the checks they provide.
- Change `Header.create(IFitsHeader...)` to allow non-matching but compatible value types.
- Rewrite `HeaderOrder` to make it more algorithmic, and less case-by-case.
- Added a bunch of new tests as necessary
=> Header checks (part 2)

src/changes/changes.xml, src/main/java/nom/tam/image/compression/hdu/CompressedImageHDU.java, src/main/java/nom/tam/image/compression/tile/TiledImageCompressionOperation.java, src/main/java/nom/tam/image/tile/operation/AbstractTiledImageOperation.java, src/main/java/nom/tam/image/tile/operation/buffer/TileBufferColumnBased.java, src/test/java/nom/tam/image/compression/tile/TileCompressionTest.java, src/test/java/nom/tam/image/compression/tile/TileCompressorProviderTest.java
Tile compression of non-square images never worked (see #129, #268). This was due to inverted tile size index ordering vs the the internal ordering used by `getAxes()`. The FITS conventiion uses Fortran style index order (with x being first), whereas java arrays have an inverted order (with x being last). The `getAxes()` method has always conformed to Java order (x being last), whereas tile sizes were in FITS order (x being first).
To reconcile, tile sizes are now stored in Java array indexing order internally s.t. the tile sizes coinform to the order returned by `getAxes()`.
=> Tile compression of non-square images

src/changes/changes.xml, src/main/java/nom/tam/fits/utilities/FitsCheckSum.java
Checksumming in-memory FITS elements (headers or data) used to require writing the data to a large-enough `byte[]` array, effectively doubling the memory requirement for data storage. This could be problematic when checksumming large data....
I reimplemented the checksumming of FITS elements to write the header or data to a `PipedOutputStream` instead, and calculate the checksum on the other end of the pipe concurrently. This way, only the memory overhead is generally small, and the performance is better due to the parallelization.
=> Checksum headers/data through pipes

src/main/java/nom/tam/fits/utilities/FitsCheckSum.java, src/main/java/nom/tam/util/FitsOutputStream.java, src/main/java/nom/tam/util/OutputEncoder.java, src/test/java/nom/tam/fits/test/BaseFitsTest.java, src/test/java/nom/tam/fits/test/ChecksumTest.java
`FitsOutputStream` did not count unencoded bytes (such as header entries) when determining whether a HDU should be written as primary or as an extension at the head of a stream. Hence, HDUs following a header-only primary HDU were incorrectly written as primary.
This pull request provides a fix to the issue.
=> Issue 368: First extension (2nd HDU) sometimes written as primary

.github/workflows/maven.yml, pom.xml, settings.xml
Unfortunately Codecov has been a pain lately, mostly not doing what it's supposed to be doing to track coverage changes. At the same time, it looks like coveralls.io is back in the game with GitHub Actions, so let's upload coverage reports to it also.
=> Coverage reporting to Coveralls.io

src/main/java/nom/tam/fits/compression/algorithm/quant/QuantizeOption.java, src/main/java/nom/tam/fits/compression/algorithm/quant/QuantizeProcessor.java, src/main/java/nom/tam/fits/compression/provider/CompressorProvider.java, src/main/java/nom/tam/fits/compression/provider/param/api/ICompressParameters.java, src/main/java/nom/tam/fits/compression/provider/param/base/BundledParameters.java, src/main/java/nom/tam/fits/compression/provider/param/base/CompressParameters.java, src/main/java/nom/tam/fits/compression/provider/param/quant/QuantizeParameters.java, src/main/java/nom/tam/fits/compression/provider/param/quant/ZDither0Parameter.java, src/main/java/nom/tam/image/compression/tile/TileCompressor.java, src/main/java/nom/tam/image/compression/tile/TileDecompressor.java, src/test/java/nom/tam/fits/compression/ReadWriteProvidedCompressedImageTest.java, src/test/java/nom/tam/fits/compression/algorithm/quant/QuantizeTest.java
This PR addresses two related issues:
1. `ZDITHER0` was not used (written or read) to record or seed the random generator when dithering.
2. Initializing the dither random generator an a per-tile basis using `ZDITHER0` as prescribed by the FITS standard.
=> Use ZDITHER0 and seed dither random generator for each tile as prescribed

src/main/java/nom/tam/fits/compression/algorithm/hcompress/HCompressor.java, src/main/java/nom/tam/fits/compression/algorithm/hcompress/HCompressorQuantizeOption.java, src/main/java/nom/tam/fits/compression/algorithm/rice/RiceCompressor.java, src/main/java/nom/tam/fits/compression/algorithm/rice/RiceQuantizeCompressOption.java, src/test/java/nom/tam/fits/compression/algorithm/hcompress/HCompressTest.java, src/test/java/nom/tam/fits/compression/algorithm/rice/RiceCompressTest.java
Some compression classes / methods were deleted with PR #350, but should be brought back to maintain back compatibility to previous releases.
=> Issue 390: Restore back compatibility for compression as closely as possible.

.github/workflows/maven.yml, codecov.yml, src/main/java/nom/tam/fits/compression/provider/CompressorProvider.java, src/main/java/nom/tam/fits/compression/provider/param/api/ICompressParameters.java, src/main/java/nom/tam/image/compression/tile/TiledImageCompressionOperation.java, src/test/java/nom/tam/image/compression/tile/TileCompressionTest.java, src/test/java/nom/tam/image/tile/operation/TileImageCompressionOperationTest.java
Compression parameters have a doubly abstracted hierarchy, based on an interface, on top of which lies an abstract class providing another layer of abstract method stems that subclasses must all implement. In effect, the abstract class does what default methods should have been used for in the base interface. This double layering of abstract methods is unfortunate, but since this is how it has been since the compression classes were added in 1.15, we have no choice but to keep it that way, lest we want to risk back compatibility issues.
The problems start when bundling options (in PR #350) that implement only the base interface, but not the additional abstract methods of the abstract class atop the interface, such as was the case for `CompressorProvider.NULL_PARAMETERS`. The problem is …
=> Fix CompressorProvider.NULL_PARAMETERS not playing nice when bundled.

src/main/java/nom/tam/fits/StreamingTileImageData.java, src/main/java/nom/tam/fits/compression/algorithm/hcompress/HCompressorQuantizeOption.java, src/main/java/nom/tam/fits/compression/algorithm/quant/QuantizeOption.java, src/main/java/nom/tam/fits/compression/algorithm/rice/RiceQuantizeCompressOption.java, src/main/java/nom/tam/fits/compression/provider/CompressorProvider.java, src/main/java/nom/tam/image/compression/CompressedImageTiler.java, src/main/java/nom/tam/image/compression/hdu/CompressedImageHDU.java, src/main/java/nom/tam/util/ArrayFuncs.java, src/site/markdown/index.md, src/test/java/nom/tam/image/compression/CompressedImageTilerTest.java, src/test/java/nom/tam/util/DefaultMethodsTest.java
A bit of an ugly one.  This is to support cutting out of Compressed images to a Stream.  We have very large cubes compressed using `fcat` that need to support streamed cutouts.  This also includes some fixes for the re-introduced `Float` support.
=> New ability to stream cutouts from compressed images

.github/workflows/gh-package.yml, .github/workflows/maven.yml, .github/workflows/site.yml
Since JDK 17 has somewhat recently became the next LTS release of Java, our github workflows should use it. This means bumping from JDK 11 to JDK 17 in `actions/setup-java@v3`
=> Use JDK 17 for CI

src/main/java/nom/tam/fits/AsciiTable.java, src/main/java/nom/tam/fits/AsciiTableHDU.java, src/main/java/nom/tam/fits/BasicHDU.java, src/main/java/nom/tam/fits/BinaryTable.java, src/main/java/nom/tam/fits/BinaryTableHDU.java, src/main/java/nom/tam/fits/Header.java, src/main/java/nom/tam/fits/TableData.java, src/main/java/nom/tam/fits/TableHDU.java, src/main/java/nom/tam/image/compression/hdu/CompressedTableData.java, src/main/java/nom/tam/util/ColumnTable.java, src/main/java/nom/tam/util/DataTable.java, src/test/java/nom/tam/fits/FitsHeapTest.java, src/test/java/nom/tam/fits/test/BinaryTableTest.java, src/test/java/nom/tam/util/FitsDecoderTest.java
Up to now, we always loaded the whole shebang of a binary table into memory as soon as we accessed a single element or row from it. But, we don't have to when using random-accessible inputs. Tables can be huge, and often we need only select elements from it (e.g. a few columns from a set of rows).
So, update `BinaryTable` to allow accessing elements and rows directly from the random-accessible input. (The heap will get lazy loaded at the first access to prevent buffer swapping between the main table and heap areas within the same file -- however heaps load fast, since it's a direct byte transfer into an `java.nio.ByteBuffer` without any processing). We still have the option to load the main table into memory as well if that is practical, using `TableHDU.getKernel()` or the equivalent …
=> Allow accessing binary table elements / rows in deferred mode

src/main/java/nom/tam/fits/header/extra/CXCStclSharedExt.java, src/main/java/nom/tam/fits/header/extra/SBFitsExt.java, src/main/java/nom/tam/fits/header/hierarch/Hierarch.java, src/main/java/nom/tam/fits/header/hierarch/IHierarchKeyFormatter.java, src/test/java/nom/tam/fits/HeaderTest.java, src/test/java/nom/tam/util/ComplexValueTest.java
Make it easier to create HIERARCH-style header keywords, by hiding the internal naming convention for such keys from users, who can instead just create the long or hierarchical FITS keywords they desire. Users can just ise one of the static `Hierarch.key()` methods to constructs HIERARCH-style keywords for use within this library. E.g.:
```java
String key = Hierarch.key("myLongFitsKeyword");
```
which sets `key` to  `HIERARCH.myLongFitsKeyword` (which is how we refer to this long keyword within the library, such as with header access methods).
or:
```java
String key = Hierarch.key("my.hierarchical.fits.keyword");
```
to set `key ` to `HIERARCH.my.hierarchical.fits.keyword`, or equivalently to the one above:
```java
String key = Hierarch.key("my", "hierarchical", "fits", "keyword");
``` …
=> Hierarch helper

src/changes/changes.xml, src/main/java/nom/tam/fits/ImageHDU.java, src/main/java/nom/tam/fits/compression/algorithm/hcompress/HCompressorOption.java, src/main/java/nom/tam/fits/compression/algorithm/rice/RiceCompressOption.java, src/main/java/nom/tam/fits/compression/algorithm/rice/RiceCompressor.java, src/main/java/nom/tam/fits/compression/provider/param/hcompress/HCompressScaleParameter.java, src/test/java/nom/tam/fits/compression/algorithm/hcompress/HCompressTest.java, src/test/java/nom/tam/fits/compression/algorithm/rice/RiceCompressTest.java
The BYTEPIX value was not properly shared across copies of `RiceCompressOption`. Fix by shared config properties in `RiceCompressOption` and also `HCompressorOption` classes. Also validate BYTEPIX and BLOCKSIZE settings (in `RiceCompressOption`) and scale parameter (in `HCompressorOption`) and throw an `IllegalArgumentException` if the set
values are invalid.
=> Issue 460 -- Rice compression BYTEPIX regression in 1.18.0-rc6

src/main/java/nom/tam/fits/FitsFactory.java, src/test/java/nom/tam/fits/BasicHDUTest.java
ASCII tables can only be read after `FitsFactory.setUseAsciiTables(true)` was set prior. This is a regression in 1.18.0.
=> Fix ASCII table read regression

pom.xml, src/main/java/nom/tam/fits/BinaryTableHDU.java, src/main/java/nom/tam/fits/compression/provider/param/base/CompressColumnParameter.java, src/main/java/nom/tam/fits/compression/provider/param/base/CompressHeaderParameter.java, src/main/java/nom/tam/image/compression/bintable/BinaryTableTile.java, src/main/java/nom/tam/image/compression/bintable/BinaryTableTileCompressor.java, src/main/java/nom/tam/image/compression/bintable/BinaryTableTileDecompressor.java, src/main/java/nom/tam/image/compression/bintable/BinaryTableTileDescription.java, src/main/java/nom/tam/image/compression/hdu/CompressedImageData.java, src/main/java/nom/tam/image/compression/hdu/CompressedImageHDU.java, src/main/java/nom/tam/image/compression/hdu/CompressedTableData.java, src/main/java/nom/tam/image/compression/tile/TiledImageCompressionOperation.java, src/main/java/nom/tam/image/compression/tile/mask/AbstractNullPixelMask.java, src/main/java/nom/tam/image/tile/operation/AbstractTiledImageOperation.java, src/main/java/nom/tam/util/BufferedFileIO.java
Various fixes and additions to API documentation. Disable warning on missing comments / tags since javadoc does not process `@SuppressWarnings("javadoc")` tags, of which have many -- resulting in a long spam of useless warnings otherwise.
=> Add some missing javadoc, disable warnings for missing comments / tags.

src/main/java/nom/tam/fits/Header.java, src/site/markdown/index.md, src/test/java/nom/tam/fits/HeaderTest.java
This new method complements the existing `Header.updateLines(Header)` method, offering different handling for conflicting header entries. Whereas `updateLines(Header)` will override existing entries for the same keywords, `mergeDistinct(Header)` will leave conflicting pre-existing entries untouched, copying only new keywords and all comments.
=> Added Header.mergeDistinct(Header source)

src/main/java/nom/tam/fits/Fits.java, src/test/java/nom/tam/fits/test/BaseFitsTest.java
This MR resolves #495.
On Windows, ``File::canWrite()`` can incorrectly return ``true`` for read-only files on network shares. This can cause ``Fits::randomInit()`` to attempt to open the read-only file in ``rw`` mode, which throws an exception because the file is not actually writable.
This MR modifies ``Fits::randomInit()`` to first attempt to open the named file in ``rw`` mode. If that fails, it then attempts to open it in read-only mode, as before.
=> Work around Windows issue with read-only files on network shares.

pom.xml, src/main/java/nom/tam/fits/AsciiTable.java, src/main/java/nom/tam/fits/BinaryTable.java, src/main/java/nom/tam/fits/BinaryTableHDU.java, src/main/java/nom/tam/fits/Data.java, src/main/java/nom/tam/fits/Fits.java, src/main/java/nom/tam/fits/HeaderOrder.java, src/main/java/nom/tam/fits/ImageData.java, src/main/java/nom/tam/fits/ImageHDU.java, src/main/java/nom/tam/fits/RandomGroupsData.java, src/main/java/nom/tam/fits/RandomGroupsHDU.java, src/main/java/nom/tam/fits/UndefinedData.java, src/main/java/nom/tam/fits/UndefinedHDU.java, src/main/java/nom/tam/fits/header/NonStandard.java, src/main/java/nom/tam/util/HashedList.java, src/site/markdown/index.md, src/test/java/nom/tam/fits/BadData.java, src/test/java/nom/tam/fits/BasicHDUTest.java, src/test/java/nom/tam/fits/BinaryTableNewTest.java, src/test/java/nom/tam/fits/BitpixTest.java, src/test/java/nom/tam/fits/DeferredTest.java, src/test/java/nom/tam/fits/ImageProtectedTest.java, src/test/java/nom/tam/fits/UndefinedDataTest.java, src/test/java/nom/tam/fits/test/AsciiTableTest.java, src/test/java/nom/tam/fits/test/BaseFitsTest.java, src/test/java/nom/tam/fits/test/ImageTest.java, src/test/java/nom/tam/fits/test/RandomGroupsTest.java, src/test/java/nom/tam/image/compression/tile/TileCompressorProviderTest.java
- Introduced `ImageData.from(Object)`, essentially offering the same behavior as the constructor with the same argument. Both now check that the argument is a valid regular primitive numerical Java array, or else throw an `IllegalArgumentException`.
- Added `Data.toHDU()` implementations, to wrap data classes into HDUs with the mandatory minimal header descriptions.
- Inspection methods for `UnknownData`.
- Header order changed s.t. EXTEND comes after GCOUNT, resulting in better conformance to the FITS standard. (EXTEND is an optional keyword. As such it must come after the mandatory keywords.)
- `Data.fillHeader()` implementations to remove SIMPLE + EXTEND or XTENSION keywords depending on which types of HDUs the data may support (`ImageData` will assume primary HDU until it becomes …
=> Targeted Data creation, improved RandomGroups and UndefinedData support

src/main/java/nom/tam/fits/FitsHeap.java, src/main/java/nom/tam/fits/PaddingException.java, src/main/java/nom/tam/fits/compression/provider/param/api/HeaderCardAccess.java, src/main/java/nom/tam/fits/utilities/FitsCheckSum.java, src/main/java/nom/tam/image/compression/tile/mask/AbstractNullPixelMask.java
spotbugs exposed potential vulnerabilities with constructors that throw exceptions. These aren't really issues with the nom-tam-fits library as the vulnerability does not expose sensitive information. However, in looking through the list, a few constructors did not declare the runtime exception they might throw, while in some cases the throwing of exceptions was completely unwarranted and should be removed.  So, taking this opportunity to clean up a little. Specifically:
- The constructor of `PaddingException` indicated it may throw a `FitsException` but of course it does not. (It extends `FitsException`). So removed the mistaken declaration.
- The constructor of `FitsCheckSum.Checksum` also indicated a runtime exception that may be thrown, but in fact it does not do that, so also removed …
=> Various fixes and javadoc updates to constructors that throw exceptions.

src/main/java/nom/tam/fits/PaddingException.java, src/main/java/nom/tam/image/compression/hdu/CompressedTableHDU.java, src/main/java/nom/tam/image/compression/tile/mask/AbstractNullPixelMask.java, src/test/java/nom/tam/image/compression/hdu/CompressedTableTest.java
Added
- `int CompressedTableHDU.getTileRows()` method to inquire how many table rows are compressed into a tile, without the user having to know about or deal with the low-level compression keywords.
- `int CompressedTableHDU.getTileCount()` method that make it easier and more transparent for users to figure out how many compressed tiles are available.
- `BinaryTableHDU asBinaryTableHDU(int tile)` for decompressing just a single table tile.
=> Methods to help selective access to compressed table tiles.

src/main/java/nom/tam/fits/AsciiTable.java, src/main/java/nom/tam/fits/AsciiTableHDU.java, src/main/java/nom/tam/fits/BinaryTable.java, src/main/java/nom/tam/fits/BinaryTableHDU.java, src/main/java/nom/tam/fits/ImageHDU.java, src/test/java/nom/tam/fits/test/AsciiTableTest.java
- Added static `AsciiTable.fromColumnMajor(Object[])` to replace deprecated `AsciiTableHDU.encapsulate(Object)` method.
- Added sanity checks to `AsciiTable.addColumn()` methods
- Some Javadoc updates to provide more elpful documentation on tables.
=> Added missing AsciiTable targeted creation method

src/main/java/nom/tam/fits/Header.java, src/main/java/nom/tam/fits/HierarchNotEnabledException.java, src/main/java/nom/tam/fits/LongStringsNotEnabledException.java, src/main/java/nom/tam/fits/LongValueException.java, src/main/java/nom/tam/fits/TableHDU.java, src/main/java/nom/tam/fits/UnclosedQuoteException.java, src/site/markdown/index.md, src/test/java/nom/tam/fits/test/HeaderCardExceptionsTest.java
Make the following soft exceptions subclasses of `HeaderCardException`:
- `LongValueException`
- `HierarchNotEnabledException`
- `LongStringsNotEnabledException`
- `UnclosedQuoteException`
since all of these are header card specific to begin with...
=> HeaderCardException subclasses

src/main/java/nom/tam/fits/BasicHDU.java, src/main/java/nom/tam/fits/Fits.java, src/main/java/nom/tam/fits/Header.java, src/main/java/nom/tam/fits/HierarchNotEnabledException.java, src/main/java/nom/tam/fits/header/Standard.java, src/main/java/nom/tam/util/HashedList.java, src/site/markdown/index.md, src/test/java/nom/tam/fits/test/BaseFitsTest.java
Add the following convenience methods:
- `Fits.getPrimaryHeader()` to get easy access to the primary header in the FITS. Unlike `Fits.getHDU(0).getHeader()` it will also populate the mandatory FITS keywords for the primary HDU's header (s.t. subsequent calls to  `Fits.getHDU(0).getHeader()` would also have those even if they weren't present before).
- `Fits.getCompleteHeader(...)` methods, which can retrieve completed headers for individual HDUs. Like above, the headers returned this way will be updated to include the mandatory FITS keywords. And, if the header has `INHERIT` set to `true`, the call will return an independent new header that is composed of the entries explicitly defined in the selected HDU, with all non-conflicting primary keys added also.
This PR also contains some fixes …
=> Support for INHERIT keyword

.classpath, src/main/java/nom/tam/fits/AsciiTable.java, src/main/java/nom/tam/fits/BinaryTableHDU.java, src/main/java/nom/tam/fits/HeaderCard.java, src/main/java/nom/tam/fits/HierarchNotEnabledException.java, src/main/java/nom/tam/fits/TableHDU.java, src/main/java/nom/tam/fits/header/Checksum.java, src/main/java/nom/tam/fits/header/Compression.java, src/main/java/nom/tam/fits/header/DataDescription.java, src/main/java/nom/tam/fits/header/DateTime.java, src/main/java/nom/tam/fits/header/FitsHeaderImpl.java, src/main/java/nom/tam/fits/header/HierarchicalGrouping.java, src/main/java/nom/tam/fits/header/IFitsHeader.java, src/main/java/nom/tam/fits/header/InstrumentDescription.java, src/main/java/nom/tam/fits/header/NonStandard.java, src/main/java/nom/tam/fits/header/ObservationDescription.java, src/main/java/nom/tam/fits/header/ObservationDurationDescription.java, src/main/java/nom/tam/fits/header/Standard.java, src/main/java/nom/tam/fits/header/Synonyms.java, src/main/java/nom/tam/fits/header/WCS.java, src/main/java/nom/tam/fits/header/extra/CXCExt.java, src/main/java/nom/tam/fits/header/extra/CXCStclSharedExt.java, src/main/java/nom/tam/fits/header/extra/MaxImDLExt.java, src/main/java/nom/tam/fits/header/extra/NOAOExt.java, src/main/java/nom/tam/fits/header/extra/SBFitsExt.java, src/main/java/nom/tam/fits/header/extra/STScIExt.java, src/site/markdown/index.md, src/test/java/nom/tam/fits/HeaderProtectedTest.java, src/test/java/nom/tam/fits/test/EnumHeaderTest.java, src/test/java/nom/tam/fits/test/HeaderCardTest.java
In `nom.tam.fits.header` package:
- New `WCS` enumerates all the FITS standard WCS keywords. Many WCS keywords support alternative coordinates, which are indicated with a trailing letter `A` through `Z`. These can be set via the `.alt(char)` method of WCS keywords. For example: `WCS.CTYPEn.n(1).alt('A')` generates the standard FITS keyword `CTYPE1A`. The `WCS` enum also contains constants that can be used as values, or for compositing appropriate values, e.g. for CTYPE<i>na</i> keywords.
- New `DateTime` enumerates all the FITS standard date-time keywords, and provides constant that can be used as specific recognised values for some of these.
- `Synonyms` has been extended to contain synonymous WCS keywords
- Added default methods to `IFitsHeader` to eliminate code that was duplicated …
=> Standardized WCS keywords etc.

src/main/java/nom/tam/fits/BasicHDU.java, src/main/java/nom/tam/fits/BinaryTable.java, src/main/java/nom/tam/fits/Header.java, src/main/java/nom/tam/fits/HeaderCard.java, src/main/java/nom/tam/fits/MismatchedValueTypeException.java, src/main/java/nom/tam/fits/ValueTypeException.java, src/main/java/nom/tam/fits/header/Standard.java, src/site/markdown/index.md, src/test/java/nom/tam/fits/HeaderTest.java, src/test/java/nom/tam/fits/KeyTypeTest.java, src/test/java/nom/tam/fits/test/HeaderCardStaticTest.java, src/test/java/nom/tam/fits/test/HeaderCardTest.java
Many mandatory/reserved FITS keywords are designated to be used with specific HDU types only, and should take only specific types of values. For example the `THEAP` keyword should appear only in binary table HDUs, and must have an integer value. Until now we allowed users both to add this keyword to other HDU types (say an image HDU), and/or to set say the value to a string such as `"blah"`. However, such misuse of keywords can be problematic for tools reading files produced by us, ans so we should not allow such abominations in the future (or, at least not by default).
Our `IFitsHeader` interface allows specifying the HDU type to which standardized keywords belong, but we have not used it thus far for checking if these keywords were used appropriately. From now on we will add the …
=> Standardized keyword and value checking

src/main/java/nom/tam/fits/Header.java, src/main/java/nom/tam/fits/HeaderCard.java, src/main/java/nom/tam/fits/header/Compression.java, src/main/java/nom/tam/fits/header/DataDescription.java, src/main/java/nom/tam/fits/header/IFitsHeader.java, src/main/java/nom/tam/fits/header/Standard.java, src/main/java/nom/tam/fits/header/Synonyms.java, src/main/java/nom/tam/fits/header/extra/NOAOExt.java, src/site/markdown/index.md, src/test/java/nom/tam/fits/HeaderTest.java, src/test/java/nom/tam/fits/ProtectedFitsTest.java
- Check that primary keywords (e.g. `SIMPLE`) are not used in extension only HDUs (such as tables).
- Check that extension only keywords (e.g. `XTENSION`) are not used in primary only HDUs (such as random groups)
- Fix log spamming when setting integer values to real-type keywords in PR #534
- Deprecate `IFitsHeader.HDU.PRIMARY_EXTENSION` (meaning primary or extension) since it is the same as `.ANY`. Refactor `PRIMARY_EXTENSION` to `ANY` in `NOAOExt` 
- `PCOUNT`, `GCOUNT` were marked as `HDU.EXTENSION`, but these are required keywords in __all__ HDUs, so change it `HDU.ANY`
- Similarly `EXTNAME`, `EXTVER`, and `EXTLEVEL` are explicitly allowed in the primary by the FITS standard so correct their assignment to `HDU.ANY` also, and add to `Synonyms` with equivalent (non-standard) `HDU...` …
=> Additional keyword checking and some fixes to PR #534

src/main/java/nom/tam/util/ByteArrayIO.java, src/main/java/nom/tam/util/ColumnTable.java
Heaps beyond 1 GB were not properly supported prior to this fix, Now they should be good up to the 2GB limit of Java `byte[]` arrays...
=> Fix heap growth beyond 1 GB.

src/main/java/nom/tam/fits/AsciiTable.java, src/main/java/nom/tam/fits/AsciiTableHDU.java, src/main/java/nom/tam/fits/BinaryTable.java, src/main/java/nom/tam/fits/BinaryTableHDU.java, src/main/java/nom/tam/fits/TableHDU.java, src/test/java/nom/tam/fits/AsciiTableNewTest.java, src/test/java/nom/tam/fits/BinaryTableNewTest.java, src/test/java/nom/tam/fits/test/AsciiTableTest.java, src/test/java/nom/tam/fits/test/BinaryTableTest.java
- `ColumnDesc.name(String)` to set user-specified column names for binary table descriptors
- `ColumnDesc.name()` to retrieve the current name of the binary table column descriptor
- `BinaryTable.indexOf(String)` to find the first column index that matches the name
- `BinaryTable.getDescriptor(String)` to return the descriptor of the first column whose name matches
- `static String TableHDU.getDefaultColumnName(int)` to return the default column name by Java column index.
- `TableHDU.setColumnName(...)` now sets the name of the column in the table in addition to setting it in the header. It will also check the column index and throw an `IndexOutOfBoundsException` if it is out of range for the table; and checks the name to ensure it contains only ASCII characters between 0x20 and 0x7E or …
=> Default column names

src/main/java/nom/tam/fits/header/Stokes.java, src/test/java/nom/tam/fits/header/StokesTest.java
The image coordinate type 'STOKES' is special, as the set of values along that 'coordinate' translate to a set of specific polarization Stokes parameters. We now add mappings between the coordinate indices and the associated parameters, and utilities to populate and parse Stokes 'coordinates' in FITS files properly.
New `Stokes` enum and its static methods can help handle these special values with ease.
=> Easier to use 'STOKES' coordinates

src/main/java/nom/tam/image/compression/hdu/CompressedTableData.java
Fixing by each column having its own independent tile indexing scheme.
(I think that was my bad -- mea culpa. I think I swapped the loop order at some point not realizing the dire consequences of it --- and since the tests all passed, I was blissfully unaware of the screw-up...)
=> Fix compressing multiple table columns

src/main/java/nom/tam/fits/Fits.java, src/main/java/nom/tam/util/ArrayFuncs.java, src/main/java/nom/tam/util/Quantizer.java, src/test/java/nom/tam/util/ArrayFuncsTest.java
Convenience methods for obtaining a sampling of an array in 1 or more dimensions, including in reversed order along individual axes. Based on discussion #618.
=> Add ArrayFuncs.sample() and .slice() methods

src/main/java/nom/tam/image/compression/hdu/CompressedTableData.java, src/main/java/nom/tam/image/compression/hdu/CompressedTableHDU.java, src/test/java/nom/tam/image/compression/hdu/CompressedTableTest.java
Do not set default column names when creating compressed tables
=> Issue #636: Keep column names in compressed tables.

README.md, pom.xml, src/main/java/nom/tam/fits/header/DataDescription.java, src/main/java/nom/tam/fits/header/DateTime.java, src/main/java/nom/tam/fits/header/InstrumentDescription.java, src/main/java/nom/tam/fits/header/ObservationDurationDescription.java, src/main/java/nom/tam/fits/header/Synonyms.java, src/main/java/nom/tam/fits/header/extra/CXCExt.java, src/main/java/nom/tam/fits/header/extra/CXCStclSharedExt.java, src/main/java/nom/tam/fits/header/extra/CommonExt.java, src/main/java/nom/tam/fits/header/extra/ESOExt.java, src/main/java/nom/tam/fits/header/extra/MaxImDLExt.java, src/main/java/nom/tam/fits/header/extra/NOAOExt.java, src/main/java/nom/tam/fits/header/extra/SBFitsExt.java, src/main/java/nom/tam/fits/header/extra/STScIExt.java, src/test/java/nom/tam/fits/header/extra/CommonExtTest.java, src/test/java/nom/tam/fits/header/extra/ESOExtTest.java
based on available documentation.
- Fix associated value types for extension keywords. They were all too often incorrect
- Add missing keywords for the MaxIm DL (`MaxImDLExt`) keyword convention.
- Add constants to define standard values where appropriate. 
- Add `CommonExt` to collect other commonly used keywords, e.g. in the amateur astronomy community (thanks @johnmurphyastro)
- Avoid duplicate definitions by referencing the parent enum values where appropriate.
- Edit standard header comment values
- Update Javadoc
=> Revised definitions of FITS keyword extensions

src/main/java/nom/tam/fits/HeaderCard.java, src/main/java/nom/tam/fits/HeaderCardFormatter.java, src/main/java/nom/tam/fits/header/hierarch/IHierarchKeyFormatter.java, src/test/java/nom/tam/fits/test/HeaderCardExceptionsTest.java, src/test/java/nom/tam/fits/test/HeaderCardTest.java
Match the calculation of space available for values in HIERARCH cards to the flexible assignment string used by PR #696. Also revise space calculations in general, to allow for maximal used of header cards space given the value constraints and FITS settings.
=> Revised calculations of space available in cards

CHANGELOG.md, src/main/java/nom/tam/util/RandomAccessFileChannel.java, src/test/java/nom/tam/util/RandomAccessFileChannelTest.java
Hi again @at88mph,
Thanks for the quick review of the changes. Unfortunately, after sleeping on it, I decided to tweak it a bit more. I could not resist another refactoring, because the class name still sounded so awkward. I also declared the methods that return concrete values as `final` as no subclasses should ever mess with these.
A bit unusually, this PR us on the same branch as the one before it, since I did not realize you have already merged the previous changes when I committed new ones.
=> Refactor (again) to RandomAccessFileChannel etc.

CHANGELOG.md, src/main/java/nom/tam/fits/compression/algorithm/api/ICompressor.java, src/main/java/nom/tam/fits/compression/provider/CompressorProvider.java, src/test/java/nom/tam/fits/compression/algorithm/hcompress/HCompressTest.java
For compression, quantization is independent from the type of compression algorithm used, so compression quantization options (`ZSCALE`, `ZZERO`, `ZBLANK`, and `ZQUANTIZ`) should be supported for all compression types. However, due to an oversight, previously we have supported quantization options only for lossy compression algorithms (which have additional compression options).
=> Enable quantization for lossless compression also

CHANGELOG.md, src/main/java/nom/tam/fits/HeaderCard.java, src/main/java/nom/tam/fits/HeaderCardParser.java, src/test/java/nom/tam/fits/HeaderTest.java, src/test/java/nom/tam/fits/test/HeaderCardTest.java
The FITS standard states:
> 4.1.2.2. Value indicator (Bytes 9 and 10)
>
> If the two ASCII characters '= ' (decimal 61 followed by decimal 32) are present in Bytes 9 and 10 of the keyword
> record, this indicates that the keyword has a value field associated with it, unless it is one of the commentary keywords
> defined in Sect. 4.4.2 (i.e., a HISTORY, COMMENT, or completely blank keyword name), which, by definition, have no value.
So, we should comply.
=> Parsing of canonical comment keys with '=' in column 9.
